apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "exporters-webhook-chart.fullname" . }}
  labels:
    app: mutateme
webhooks:
  - name: mutateme.{{ .Release.Namespace }}.svc.cluster.local
    clientConfig:
      service:
        name: {{ include "exporters-webhook-chart.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: {{ .Values.service.port }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
