name: nginx-exporter
image: nginx/nginx-prometheus-exporter:0.4.2
ports:
  - containerPort: 9113
resources:
  requests:
    memory: 10Mi
    cpu: 10m
  limits:
    memory: 50Mi
    cpu: 200m
args: ["-nginx.scrape-uri", "http://localhost:81/nginx-status"]
