apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: utils
  labels:
    app: nginx-test
    exporter-injection: "enabled"
  annotations:
    inject-exporters: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
        inject-exporters: "nginx"
        exporter-injection: enabled
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10-alpine
